### ISSUE TITLE
AoE2Tools didn't and still can't succesfully set hotkeys

### ISSUE THREAD

**Issue by henkieaardpeer** [gregstein/AoE2Tools#24] opened 2019-09-13 15:00 UTC
Another issue, during installation I chose ''HD hotkeys'' to be used in Voobly, but I think I have the Age of Conquerors ones (tried by hosting a game with AI a few times). I am saying this for two reasons:
-Might be a bug in the installation tool
-Even if I set it in the program now, it still doesn't work when I launch a test Voobly game

**Comment by gregstein** [comment] 2019-09-13 15:35
Hello,

Until I investigate that here download this HD hotkeys profile and use Restore button http://prntscr.com/p5qnfe to install them: 

[hd_hotkeys.zip](https://github.com/gregstein/AoE2Tools/files/3610681/hd_hotkeys.zip)

**Comment by kansha-gratitude** [comment] 2019-09-13 19:38
Unfortunately, this does not work. 

I tried it several times, and when it didn't work, I tried just selecting ''HD hotkeys'' from the drop-down menu again, but nothing helps. Completely restarted Voobly several times in the process, hosting games with only myself and then adding an AI to simulate a game. The mods from the other thread are gone, but the hotkey stuff is not fixed.

**Comment by gregstein** [comment] 2019-09-13 19:45
Thank you for reporting back. Allow me a few minutes I test it myself and reply to you with a guaranteed solution.

**Comment by gregstein** [comment] 2019-09-13 19:57
Hello again,

I think it was way easier than I thought. First double check if these are the correct hotkeys https://aokhotkeys.appspot.com/presets/get/2341004

On hd create villager is on key 'A' right? if that is so you can proceed with downloading this file
https://www.mediafire.com/file/nws6idt55m2bwon/player0.hki (Sorry couldn't upload it here)

Then browse and select that file you downloaded "player0.hki" then hit install e.g. http://prntscr.com/p5tu45


This website, https://aokhotkeys.appspot.com/presets  provides lots of hotkey profiles which you can download but make sure to select **AoC/FE/HD2.0** before you hit generate download file e.g. http://prntscr.com/p5tvte
I tested myself and hotkeys installed for both wk mod and aoc. 

If you need further help feel free to join discord and I could even assist you through Anydesk if you want to.

**Comment by kansha-gratitude** [comment] 2019-09-13 20:14
I will come back to this tomorrow.

**Comment by gregstein** [comment] 2019-09-13 21:32
Sure brother! Have a great rest of your day.

**Comment by kansha-gratitude** [comment] 2019-09-15 15:32
There's two things I would like to ask you:
-Could you upload the Mediafire file elsewhere? I am too paranoid to use such websites anymore
-I don't understand the middle part:

_On hd create villager is on key 'A' right? if that is so you can proceed with downloading this file
https://www.mediafire.com/file/nws6idt55m2bwon/player0.hki (Sorry couldn't upload it here)

Then browse and select that file you downloaded "player0.hki" then hit install e.g. http://prntscr.com/p5tu45

This website, https://aokhotkeys.appspot.com/presets provides lots of hotkey profiles which you can download but make sure to select AoC/FE/HD2.0 before you hit generate download file e.g. http://prntscr.com/p5tvte
I tested myself and hotkeys installed for both wk mod and aoc._

It sounds as if I have to download and install two seperate things or in any case, when you posted this I got more confused by it than was intended.

--

Also, have you seen this issue with HD hotkeys?
https://steamcommunity.com/app/221380/discussions/2/558746745754119670/

I have been playing a bit more on HD and I am having this issue, especially with the Treb packing (x) which doesn't work and sometimes overlaps with a formation command below which is also x. Do you have any personal alternative hotkeys that wouldn't mess up the rest of the existing hotkeys?

**Comment by gregstein** [comment] 2019-09-15 16:47
Hello again,

Sorry for confusing you! No you dont install twice. The second part was just a suggestion for you to check other hotkey profiles if you want to use them. Anyways let's ignore the previous post and let's proceed first with installing hd hotkeys.

Easy Peasy Lemon Squeazy:

**Step1:** Download this zip file then you extract "player0.hki" it to desktop .
[player0.zip](https://github.com/gregstein/AoE2Tools/files/3613979/player0.zip)

**Step2:** Run AoE2Tools > Hotkeys e.g. http://prntscr.com/p6fca2

**Step 3:** Browse & Install "Player0.hki" you have extracted earlier e.g. http://prntscr.com/p6fdn2

Done. Now your HD hotkeys are installed.

Earlier I asked you if you press hotkey 'A' on your keyboard to create a villager on HD? if that is so the above installation is correct. 

For now just run the game and see if your hotkeys are there. If they are not contact me back so we can do screen-sharing through discord or remote desktop help through Anydesk.

**Comment by kansha-gratitude** [comment] 2019-09-25 16:20
Took me some time to act, but this time it worked and I also saw you changed something in your latest update. Thanks and I'll close this thread.

**Closed as completed by kansha-gratitude** 2019-09-25 16:20 UTC

**Comment by gregstein** [comment] 2019-09-25 16:27
No problem! And Thank you so much for the inspiration and the support <3
